language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3
script: /usr/bin/env php tests/run-tests.php
before_script:
  - createdb fblog -U postgres
  - psql fblog postgres < tests/fblog.sql
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - ls -l vendor/*
