language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3
script: php tests/run-tests.php
before_script:
  - composer install
  - cat vendor/composer/autoload_psr4.php
  - createdb fblog -U postgres
  - psql fblog postgres < tests/fblog.sql